First version of train-test-split
Aarhus-Psychiatry-Research/psycop-train-test-split pull request #1
Opened 2022-03-25 14:42 UTC by martbern

Research-code, so I think we can accept poorer documentation?

I've set a constant `random_state`, but in case we get more patients in a future dataset, this will probably not be stable.

We'll have to then split only the new patients, and then append those rows to our .csv. But I think that's OK.

I imagine the splits will be stored on MidtX, but we might want to ensure that there's proper backup of that!

Otherwise, does this look good to you guys?

2022-03-28 12:58 UTC, HLasse approved these changes
Der skal måske lige pilles lidt ved nogle `test_size` men ellers ser det fint ud!

2022-03-28 12:58 UTC, HLasse commented on tests/test_adding_outcomes.py
> +    outcome_df = str_to_df(outcome_str)
```suggestion
all_patients_df = pd.DataFrame({"dw_ek_borger" : [1, 2, 3, 4]})
outcome_df = pd.DataFrame({"dw_ek_borger" : [1, 2]})
```

2022-03-29 08:01 UTC, KennethEnevoldsen requested changes
What does MVP stand for?

We should probably make sure that versioning works (both to prevent breaks and reproducibility). This is very easily done by setting up the pypi workflow. You can see an example [here](https://github.com/centre-for-humanities-computing/conspiracies). 

We also need to add a workflow for running the pytest (otherwise I might not believe that they pass ;) ) again the code for that is you can also find in the conspiracies project.

It might also be nice to add the black formatting while you are at it.

If you want I can also add the workflows?

2022-03-29 08:01 UTC, KennethEnevoldsen commented on .gitignore
> +.=.swp
What is this?

2022-03-29 08:01 UTC, KennethEnevoldsen commented on requirements.txt
> +sklearn
versioning is important (especially for research code)

2022-03-29 08:01 UTC, KennethEnevoldsen commented on requirements.txt
> +git+https://github.com/Aarhus-Psychiatry-Research/utilities
we should probably make it pip installable? To ensure we can version it. (otherwise updated to utilities can cause break in MVP and the code does reproduce)

2022-03-29 08:01 UTC, KennethEnevoldsen commented on setup.cfg
> +    pandas
doesn't match with requirements.txt

2022-03-29 08:01 UTC, KennethEnevoldsen commented on setup.cfg
> +
```suggestion
```

2022-03-29 08:01 UTC, KennethEnevoldsen commented on .gitignore
>  .Renviron
```suggestion
# R Prog.
.Renviron
```

2022-03-29 08:01 UTC, KennethEnevoldsen commented on requirements.txt
> +pytest
```suggestion
# Formatting
black

# Testing
pytest
```

2022-03-29 09:55 UTC, martbern commented
> What does MVP stand for? Edit: Ahh minimal viable product. I would change that to something meaningful in the context of the code.
> 
> We should probably make sure that versioning works (both to prevent breaks and reproducibility). This is very easily done by setting up the pypi workflow. You can see an example [here](https://github.com/centre-for-humanities-computing/conspiracies).
> 
> We also need to add a workflow for running the pytest (otherwise I might not believe that they pass ;) ) again the code for that is you can also find in the conspiracies project.
> 
> It might also be nice to add the black formatting while you are at it.
> 
> If you want I can also add the workflows?
> 
> Edit: Add a minimal readme of what the repo contains

Strong agree. I'll add pytest here, but I think we shoudl save the rest of the boilerplate

2022-03-29 09:59 UTC, martbern commented on .gitignore
> +.=.swp
Python cache-files.

2022-03-29 09:59 UTC, martbern commented on requirements.txt
> +git+https://github.com/Aarhus-Psychiatry-Research/utilities
Strong agree! Added issue on `python-utilities` [here](https://github.com/Aarhus-Psychiatry-Research/python-utilities/issues/3).

2022-03-29 09:59 UTC, KennethEnevoldsen commented
Hmm maybe it is easier to save to boilerplate for now and simply add it to the new repo as discussed.

2022-03-29 10:02 UTC, martbern commented
Haha, well, now you get the tests ;-)

2022-03-29 10:03 UTC, martbern commented
Huh, that's a problem. Can't install dependencies because it's from a private repo. Might want to make our python-utilities repo public?

2022-03-29 10:04 UTC, martbern commented
Anywho, I just ran the tests locally, and they pass. Perhaps we should merge this PR, and then I'll move everything to `python-utilities`?

2022-03-29 10:05 UTC, KennethEnevoldsen commented
Another great reason for creating a joint repo ;)

2022-03-29 10:07 UTC, KennethEnevoldsen commented
maybe rename python utilities then to something more informative. Python utilities could be any function in python - psycop-utilities is utilities specifically for psycop, but I could imagine that there is a better name.

2022-03-29 10:45 UTC, merged