Allow for stratification across categories, not considering each combination a stratum (see #2)
Aarhus-Psychiatry-Research/psycop-train-test-split pull request #3
Opened 2022-04-06 14:34 UTC by martbern

2022-04-07 09:07 UTC, martbern commented
@KennethEnevoldsen, unsure why the black action is failing. It says invalid `GITHUB_TOKEN`, but the action doesn't require it, nor is it in the repo secrets D:

2022-04-08 12:05 UTC, HLasse requested changes
Good job! 🙌  Add a few more comments to the application script - otherwise good to go

2022-04-08 12:05 UTC, HLasse commented on src/psycoptts/stratify_by_each_category_individually.py
> +
add docstring

2022-04-08 12:05 UTC, HLasse commented on src/psycoptts/stratify_by_each_category_individually.py
> +    test_size=Union[float, int],
```suggestion
    test_size=float,
```

2022-04-08 12:05 UTC, HLasse commented on src/psycoptts/stratify_by_each_category_individually.py
> +        target_total_n_in_test = test_size * df.shape[0]
```suggestion
    target_total_n_in_test = test_size * df.shape[0]
```

2022-04-08 12:05 UTC, HLasse commented on src/application/create_train_test_split.py
>      val_and_test_prop = 0.3
call it `train_prop` instead

2022-04-11 16:23 UTC, KennethEnevoldsen commented on src/application/create_train_test_split.py
> +    X_train, X_intermediate = stratified_split_by_each_category(
This is fine, but wanted to mention that python typically use `_` to denote intermediate values. E.g. `X_` (not to be confused with just `_` which is a variables not intended to be used)

2022-04-11 16:23 UTC, KennethEnevoldsen commented on src/psycoptts/stratify_by_each_category_individually.py
> +        )
An easy fix here is to have the list be sets (reduced the lookup complexity from O(n) to O(1)).

2022-04-13 08:55 UTC, KennethEnevoldsen approved these changes

2022-04-13 08:55 UTC, KennethEnevoldsen commented on src/application/create_train_test_split.py
> +    msg.good("Starting test/val split")
```suggestion
    msg.info("Starting test/val split")
```

2022-04-13 08:55 UTC, KennethEnevoldsen commented on src/application/create_train_test_split.py
> +        )
brug msg

2022-04-13 08:57 UTC, merged